AG-41223 update node to v22 and pnpm to v10 [aglint]
Squashed commit of the following:

commit 873b2b4132b0adc493250201339ffa10569ef035
Author: scripthunter7 <d.tota@adguard.com>
Date:   Mon Apr 7 17:57:10 2025 +0200

    add protection for packageManager field

commit 529907bb567386fcd96345be4fa3ef291c6279e6
Author: scripthunter7 <d.tota@adguard.com>
Date:   Mon Apr 7 17:55:30 2025 +0200

    remove packageManager field

commit 868b3e177566a468684df7553102c7c86bc20429
Author: scripthunter7 <d.tota@adguard.com>
Date:   Mon Apr 7 17:52:14 2025 +0200

    update gitignore

commit 9e689561903abdf9053b3daf25373252c3e53dd0
Author: scripthunter7 <d.tota@adguard.com>
Date:   Mon Apr 7 12:24:46 2025 +0200

    update node to v22 and pnpm to v10

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,3 +1,25 @@
-yarn check-types
-yarn lint
-yarn test
+# Exit immediately if a command fails
+set -e
+
+pnpm check-types
+pnpm lint
+pnpm test
+
+if git diff --cached --name-only | grep -q "package.json"; then
+    echo "package.json is being committed. Checking if packageManager field is present..."
+
+    if pnpm pkg get packageManager > /dev/null 2>&1; then
+        echo "packageManager field in package.json is present, need to remove it before committing"
+
+        PACKAGE_JSON_HASH=$(git hash-object -w package.json)
+
+        pnpm pkg delete packageManager
+        echo "packageManager field removed from package.json"
+
+        git add package.json
+        echo "modified package.json staged for commit"
+
+        git cat-file -p "$PACKAGE_JSON_HASH" > package.json
+        echo "package.json content restored"
+    fi
+fi
